#!/bin/sh

output_config() {
    echo "graph_title Example graph"
    echo "users.label Number of users"
}

output_values() {
    printf "users.value %d\n" $(number_of_users)
}

number_of_users() {
    jq "." /tmp/useractivity.json | grep "userName"| wc -l
}

output_usage() {
    printf >&2 "%s - munin plugin to graph an users value\n" ${0##*/}
    printf >&2 "Usage: %s [config]\n" ${0##*/}
}

case $# in
    0)
        output_values
        ;;
    1)
        case $1 in
            config)
                output_config
                ;;
            *)
                output_usage
                exit 1
                ;;
        esac
        ;;
    *)
        output_usage
        exit 1
        ;;
esac